# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /list/:year/:month/:day/:title

# Setup
title:            'Predlošci za Reklamacije.net'
tagline:          'Pomažemo vam u pisanju i slanju reklamacija'
description:      'Na ovoj stranici pronaći ćete pripremljene predloške za slanje reklamacija'
url:              'http://podnesi.reklamacije.net'
baseurl:          ''

# Navigation
navigation:
- text: Početna
  url: /
- text: Popis
  url: /list/
- text: Oznake
  url: /tags/
- text: Dnevnik
  url : /archive/


# Author Details
author:         'Code for Croatia'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/programirajzahrvatsku'
flickr:
github:         'https://github.com/codeforcroatia'
gplus:
instagram:
pinterest:
linkedin:
rss:
stackoverflow:
twitter:        'https://twitter.com/codeforcroatia'

# Site analytics
analytics:
  provider: google
  google:
    id: UA-2846894-4

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler:

# txtpen
txtpenhandler:

# Github
project-repository: reklamacijenet-podnesi

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/list/page:num'
destination: ./_site

# Custom variables
version:          0.20

## Alaveteli collection

alaveteli:
  url: 'http://reklamacije.net'
  
entity:
  -
      page_category: ZGH
      name: Zagrebački holding
      slug: zagrebacki_holding_doo
  -
      page_category: 'ZET'
      name: Zagrebački električni tramvaj
      slug: zet
  -
      page_category: KBC
      name: Klinički bolnički centar Zagreb
      slug: kbc_zagreb
